# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-07 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_remove_step_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
